### ISSUE TITLE
"Certificate" in version "cert-manager.io/v1alpha2" not available 

### ISSUE THREAD

**Issue by phill1234** [puzzle/cert-manager-webhook-dnsimple#15]
Hey ho, thank you for your project!
I wanted to use it in my cluster but i use the cert-manager in version 1.6.1 and so the Certificate and Issuer from your project can't be applied according to [upgrading 1.5-1.6](https://cert-manager.io/docs/installation/upgrading/upgrading-1.5-1.6/).
Is it possible to raise the versions? Hope, there are not more upgrade issues coming :D 
All the best!

**Comment by parmus** [comment]
https://github.com/neoskop/cert-manager-webhook-dnsimple/pull/16 fixes this (at least the part in Helm chart)

**Comment by arnediekmann** [comment]
This should be fixed by the pull request by @parmus (thanks again!). Please do try version `0.1.1` of the helm chart.
