### ISSUE TITLE
no published docker image supporting arm (raspberry pi)

### ISSUE THREAD

**Issue by tonysurma** [puzzle/cert-manager-webhook-dnsimple#17]
Was so thankful when I found this for dnsimple but it appears there is no arm published image in the repository `neoskop/cert-manager-webhook-dnsimple` that supports arm.  Therefore I get the exec format error on my raspberry pi 4 cluster.

I am investigating some of the forks of this project as it looks like they may have added that but hoping you can publish arm images along with amd64.

Thanks in advance

**Comment by tonysurma** [comment]
I need to test it works but I just gen'd up images and pushed them live https://hub.docker.com/r/monkeychatter/cert-manager-webhook-dnsimple/tags

For reference, I used the buildx command described here and it built them first try for both amd64 and arm64 on my PC

**Comment by tonysurma** [comment]
I can confirm just simply building for arm worked and I was able to generate certs from letsencrypt with dnsimple.  Awesome

**Comment by troywilson** [comment]
Thanks for providing these images @tonysurma worked fine for me.

**Comment by moll-re** [comment]
As of now you can pull arm64 releases
```
docker pull ghcr.io/puzzle/cert-manager-webhook-dnsimple:v1.3 
```
