### ISSUE TITLE
Token creation

### ISSUE THREAD

**Issue by obeyler** [puzzle/cert-manager-webhook-dnsimple#21]
Secret token creation is truncated if we use this kind of token :
```
dnsimple:
  token: "9irzedrtrtbvDDZWHom2$asF"

```
At the end, the secret only contains:
'9irzedrtrtbvDDZWHom2'

$asF is missing

**Comment by moll-re** [comment]
Can you make sure the string for the token is either `base64`-encoded or the secret use `stringData` instead of `data`?
