### ISSUE TITLE
Feature request: arm64 support

### ISSUE THREAD

**Issue by iMartyn** [puzzle/cert-manager-webhook-dnsimple#24]
Yeah, I'm running an arm cluster and want to attempt getting this up and running.

The best way to do this would be to switch to ko instead of docker build as building go stuff in docker for multi-arch is painful (arm emulation is slow).

I could probably knock up a PR for your release.sh to do this (I'm currently testing on a fork with github actions) if you want?

**Comment by arnediekmann** [comment]
Hi @iMartyn, that sounds good, but how would that work exactly? I.e. don't I need to somehow build Docker images for distribution anyway? But if it is a straight-forward process I can for sure do it!

**Comment by iMartyn** [comment]
`ko` builds docker images for multiple architectures without using docker. It uses go's native building and then builds a container from it.
This is how I'm doing it at the moment (work account 'cos I made the fork on the wrong account), and aside from the binding to port 443 being an issue (which would be nice to fix too) it's working and really very simple :
https://github.com/martyn-meister/cert-manager-webhook-dnsimple/blob/master/.github/workflows/main.yml

**Comment by moll-re** [comment]
As of now you can pull arm64 releases
```
docker pull ghcr.io/puzzle/cert-manager-webhook-dnsimple:v1.3 
```
