### ISSUE TITLE
OpenAPI spec for "v1alpha1.[groupName]" failed with: failed to download v1alpha1.[groupName]: resource not found

### ISSUE THREAD

**Issue by gotascii** [puzzle/cert-manager-webhook-dnsimple#44]
I'm seeing lots of the following log spam in my k3s logs:

```
Jul 24 10:00:48 node1 k3s[10271]: E0724 10:00:48.961900   10271 controller.go:146] Error updating APIService "v1alpha1.[groupName]" with err: failed to download v1alpha1.[groupName]: resource not found
Jul 24 10:00:49 node1 k3s[10271]: E0724 10:00:49.963537   10271 controller.go:102] loading OpenAPI spec for "v1alpha1.[groupName]" failed with: failed to download v1alpha1.[groupName]: resource not found
```

where `[groupName]` is the groupName provided when installing. I _think_ it is the same issue as https://github.com/kelvie/cert-manager-webhook-namecheap/issues/7 and https://github.com/cert-manager/webhook-example/issues/27 which indicate that bumping the cert-manager mod dep up to at least 1.13 fixes the issue. I might try to give this a go on my own and generate a PR, but I'm very new to kubernetes and don't really know what I am doing :D

**Comment by klopfenstein-puzzle** [comment]
Hello, thanks for reporting this issue.  
Currently, our dependabot has already tried bumping this dep to >`1.13.0` but checks are failing.  
I'm trying to investigate as to hwo.

**Comment by klopfenstein-puzzle** [comment]
I've released a new version `v.0.1.4` with said dependency bumped to the newest version.  
Try updating your deployment and see if that resolved your issue?

Simply setting `image.tag: v0.1.4` in your `values.yaml` should suffice.

**Comment by gotascii** [comment]
Upgraded and been watching the logs, as far as I can tell this looks fixed to me! Thanks a bunch, much appreciated!

**Comment by klopfenstein-puzzle** [comment]
Good to hear! We've been observing the same on our end with this new version as well, so I believe this issue can be considered fixed and thus closed.
